/* Learning tools share MassCore.calculate; no network or stored personal data. */
(function(){
'use strict';
const C=MassCore,D=MassData, $=id=>document.getElementById(id), fmt=n=>Math.round(n).toLocaleString('en-US');
let active, last, pending=null, permit=false, points=0, solved=new Set(), question=0, category='detective';
const panel=document.createElement('section'); panel.className='learning card';
panel.innerHTML=`<div class="section-label">MASS LAB <span id="lab-score">0 learning points</span></div><p>Predict. Change the load. Explain the result.</p><label><input id="predict-toggle" type="checkbox"> Ask me before load changes</label><div id="change-log" role="status">Add a load to see what changes.</div><details open><summary>Build each mass with colours</summary><p class="legend">■ Empty aircraft · ■ Crew + items · ■ Traffic · ■ Takeoff fuel · ■ Taxi fuel</p><div id="mass-parts"></div></details><button id="reset-learning">Reset learning points</button><button id="open-lab" class="primary">Open learning challenges</button><button id="open-review">Review this flight</button><div id="flight-review"></div>`;
document.querySelector('.mass-column').append(panel);
const dialog=document.createElement('dialog');dialog.id='learning-dialog';document.body.append(dialog);
const predict=document.createElement('dialog');predict.id='prediction-dialog';predict.innerHTML='<h2>Predict before you load</h2><p id="prediction-text"></p><label>Which mass? <select id="prediction-mass"></select></label><div id="prediction-choices"><button data-predict="up">Goes up</button><button data-predict="same">No change</button><button data-predict="down">Goes down</button></div><p id="prediction-feedback" role="status"></p><button id="prediction-cancel">Cancel change</button>';document.body.append(predict);
Object.entries(D.labels).forEach(([k,v])=>$('prediction-mass').add(new Option(v[0],k)));
function award(key){if(!solved.has(key)){solved.add(key);points+=10;$('lab-score').textContent=points+' learning points';}}
window.MassLessons={allow(s,k,dir){if(permit){permit=false;return true;}if(!$('predict-toggle').checked)return true;const copy=JSON.parse(JSON.stringify(s));if(!C.change(copy,k,dir))return false;pending={s,k,dir,a:C.calculate(s),b:C.calculate(copy)};$('prediction-text').textContent=(dir>0?'Add ':'Remove ')+D.unit[k]+' kg of '+({crew:'crew',items:'operating items',passengers:'passengers',bags:'bags',cargo:'cargo',takeoffFuel:'takeoff fuel',taxiFuel:'taxi fuel'}[k])+'. Pick a mass and predict its change.';$('prediction-feedback').textContent='';predict.showModal();return false;}};
$('prediction-choices').onclick=e=>{const b=e.target.closest('[data-predict]');if(!b||!pending)return;const k=$('prediction-mass').value,d=pending.b[k]-pending.a[k],answer=d>0?'up':d<0?'down':'same';if(b.dataset.predict!==answer){$('prediction-feedback').textContent='Try again. Think about the parts inside this mass.';return;}award('predict-'+pending.k+'-'+pending.dir+'-'+k);const {k:load,dir}=pending;pending=null;predict.close();permit=true;document.querySelector('[data-load="'+load+'"][data-dir="'+dir+'"]').click();};
$('prediction-cancel').onclick=()=>{pending=null;predict.close();};predict.addEventListener('cancel',()=>pending=null);
const colors=['#456b86','#9570b1','#09816d','#e2a536','#cf6b48'];
function parts(s,a){const base=[[4000,'Empty aircraft'],[a.dom-4000,'Crew + items'],[a.traffic,'Traffic'],[s.loads.takeoffFuel,'Takeoff fuel'],[s.loads.taxiFuel,'Taxi fuel']];const map={bem:[0],dom:[0,1],om:[0,1,3],traffic:[2],zfm:[0,1,2],useful:[2,3],taxiMass:[0,1,2,3,4],tom:[0,1,2,3],lm:[0,1,2,3]};return Object.entries(map).map(([k,ids])=>{const segments=ids.map(i=>({n:k==='lm'&&i===3?Math.max(0,s.loads.takeoffFuel-s.tripFuel):base[i][0],label:k==='lm'&&i===3?'Landing fuel':base[i][1],i}));if(k==='lm'&&a.landingFuel<0)return '<p>LM: add enough trip fuel first.</p>';return '<div class="parts-row"><b>'+D.labels[k][0]+'</b><div class="parts-bar">'+segments.filter(v=>v.n).map(v=>'<span style="flex:'+v.n+';background:'+colors[v.i]+'" title="'+v.label+': '+v.n+' kg"></span>').join('')+'</div><small>'+segments.map(v=>v.label+' '+fmt(v.n)).join(' + ')+' = '+fmt(a[k])+' kg'+(['lm','tom','taxiMass'].includes(k)?' (stage value)':'')+'</small></div>';}).join('');}
window.addEventListener('mass-render',e=>{const {state:s,values:a}=e.detail;active=s;const fresh=last!==s;if(fresh){pending=null;permit=false;if(predict.open)predict.close();$('change-log').textContent='Add a load to see what changes.';$('flight-review').innerHTML='';}if(!fresh&&s.mode!=='practice'&&e.detail.previous){const changed=Object.keys(D.labels).some(k=>e.detail.previous[k]!==a[k]);if(changed)$('change-log').innerHTML='<b>Last change</b><div class="delta-grid">'+Object.keys(D.labels).map(k=>{const d=a[k]-e.detail.previous[k];return '<span>'+D.labels[k][0]+' <b class="'+(d?'delta':'')+'">'+(d?(d>0?'+':'')+fmt(d)+' kg':'No change')+'</b></span>';}).join('')+'</div>';}
$('mass-parts').innerHTML=s.mode==='practice'&&!s.solved?'<p>Answer first to reveal the coloured parts.</p>':parts(s,a);last=s;});
const banks={
 detective:[
 ['Find the error: DOM 4,400; traffic 1,000; fuel 600. A sheet says ZFM = 6,000.','What is wrong?',['Fuel was added to ZFM','Crew was not counted','Taxi fuel is too low'],0,'ZFM = DOM + Traffic Load = 5,400 kg. Fuel is not part of ZFM.'],
 ['8 passengers at 80 kg, 8 bags at 20 kg, cargo 200 kg. A sheet says Traffic Load = 1,160.','Find the mistake.',['Bags were counted twice','Crew belongs in traffic','Fuel is missing'],0,'640 + 160 + 200 = 1,000 kg. Passenger mass excludes bags.'],
 ['Taxi Mass 6,050; taxi fuel 50. A sheet says TOM = 5,950.','Find the mistake.',['Taxi fuel was subtracted twice','Trip fuel is too high','ZFM includes fuel'],0,'Taxi fuel is used once. TOM = 6,000 kg.'],
 ['TOM 6,000; trip fuel 400; takeoff fuel 600. A sheet says LM = 5,400.','Which fuel should be subtracted?',['Trip fuel only','All takeoff fuel','Taxi fuel again'],0,'LM = 6,000 − 400 = 5,600 kg. Landing fuel is 200 kg.']
 ],
 missing:[
 ['DOM = 4,400 kg. ZFM = 5,400 kg.','Find Traffic Load (kg).',null,1000,'Traffic Load = ZFM − DOM = 1,000 kg.'],
 ['OM = 5,000 kg. DOM = 4,400 kg.','Find takeoff fuel (kg).',null,600,'Takeoff fuel = OM − DOM = 600 kg.'],
 ['TOM = 6,000 kg. Useful Load = 1,600 kg.','Find DOM (kg).',null,4400,'DOM = TOM − Useful Load = 4,400 kg.'],
 ['TOM = 6,000 kg. LM = 5,600 kg.','Find trip fuel (kg).',null,400,'Trip fuel = TOM − LM = 400 kg.'],
 ['DOM = 4,400 kg. BEM = 4,000 kg. Crew = 200 kg.','Find operating items (kg).',null,200,'4,400 − 4,000 − 200 = 200 kg.'],
 ['Taxi Mass = 6,050 kg. TOM = 6,000 kg.','Find start and taxi fuel (kg).',null,50,'6,050 − 6,000 = 50 kg.']
 ],
 compare:[
 ['Both aircraft have DOM 4,400 and trip fuel 400. A: traffic 1,000, takeoff fuel 600. B: traffic 800, takeoff fuel 800.','Which aircraft has higher ZFM?',['A','B','Same'],0,'Both TOMs are 6,000. A ZFM is 5,400; B ZFM is 5,200. More fuel does not raise ZFM.'],
 ['Use the same two aircraft. Both TOMs are 6,000. Both use 400 kg trip fuel.','Which has higher LM?',['A','B','Same'],2,'Both land at 5,600 kg, but A has 200 kg landing fuel and B has 400 kg.'],
 ['Both TOMs are 6,000. MZFM is 5,300. A ZFM is 5,400. B ZFM is 5,200.','Which passes the ZFM limit?',['A only','B only','Both'],1,'B only. Equal TOM does not mean equal ZFM.']
 ]};
function comparison(){return '<table><caption>Fictional training loads · kg</caption><tr><th>Mass</th><th>A</th><th>B</th></tr>'+['dom','traffic','zfm','tom','lm','landingFuel'].map(k=>{const a=C.create(),b=C.create();a.loads={...D.guide};b.loads={...D.guide,cargo:0,takeoffFuel:800};return '<tr><th>'+(D.labels[k]?.[0]||'Landing fuel')+'</th><td>'+fmt(C.calculate(a)[k])+'</td><td>'+fmt(C.calculate(b)[k])+'</td></tr>';}).join('')+'</table>';}
function draw(){const q=banks[category][question],done=solved.has(category+question);dialog.innerHTML='<button id="close-lab" class="dialog-close">Close ×</button><h2>Learning challenges</h2><nav class="lab-tabs">'+Object.entries({detective:'Find the error',missing:'Missing mass',compare:'Compare loads'}).map(([k,v])=>'<button data-cat="'+k+'" aria-pressed="'+(category===k)+'">'+v+'</button>').join('')+'</nav><p>Question '+(question+1)+' / '+banks[category].length+' · No timer · +10 points once</p><h3>'+q[0]+'</h3><p>'+q[1]+'</p><div id="lab-answer">'+(done?'<p>✓ '+q[4]+'</p>'+(category==='compare'?comparison():''):q[2]?q[2].map((a,i)=>'<button data-choice="'+i+'">'+a+'</button>').join(''):'<form id="lab-form"><label for="lab-number">Mass in kg</label><input id="lab-number" type="number" min="0" step="1" required><button>Check answer</button></form>')+'</div><p id="lab-feedback" role="status"></p><div class="lab-nav"><button id="lab-prev" '+(!question?'disabled':'')+'>Previous</button><button id="lab-next" '+(question===banks[category].length-1?'disabled':'')+'>Next</button></div>';}
function answer(v){const q=banks[category][question];if(solved.has(category+question))return;if(String(v).trim()!==''&&Number(v)===q[3]){award(category+question);draw();}else $('lab-feedback').textContent='Not yet. Try again. Check which loads belong in the formula.';}
dialog.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='close-lab')dialog.close();else if(b.dataset.cat){category=b.dataset.cat;question=0;draw();}else if(b.dataset.choice!==undefined)answer(b.dataset.choice);else if(b.id==='lab-next'){question++;draw();}else if(b.id==='lab-prev'){question--;draw();}};dialog.onsubmit=e=>{e.preventDefault();answer($('lab-number').value);};
$('reset-learning').onclick=()=>{solved.clear();points=0;$('lab-score').textContent='0 learning points';$('flight-review').innerHTML='';};
$('open-lab').onclick=()=>{draw();dialog.showModal();};
$('open-review').onclick=()=>{if(!active||active.stage!=='land'||active.mode==='practice'){$('flight-review').textContent='Complete a Learn or Mission flight first.';return;}const a=C.calculate(active);$('flight-review').innerHTML='<h3>Your flight · kg</h3><ol><li>At the stand: '+fmt(a.taxiMass)+'</li><li>Taxi uses '+fmt(active.loads.taxiFuel)+' → TOM '+fmt(a.tom)+'</li><li>Flight uses '+fmt(active.tripFuel)+' → LM '+fmt(a.lm)+'</li></ol><p>ZFM stayed '+fmt(a.zfm)+'. Landing fuel: '+fmt(a.landingFuel)+'.</p><p>Why did current mass fall?</p><button data-review="wrong">Passengers left</button><button data-review="right">Fuel was used</button><p id="review-feedback" role="status"></p>';};
$('flight-review').onclick=e=>{const b=e.target.closest('[data-review]');if(!b)return;$('review-feedback').textContent=b.dataset.review==='right'?'Correct. Taxi and trip fuel were used once. ZFM did not change.':'Try again. Traffic Load stayed on board.';if(b.dataset.review==='right')award('review-'+active.mode+'-'+active.missionIndex);};
})();
